name: max_sports
description: A new Flutter project.

publish_to: 'none'

version: 1.1.2+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.2.0
  path:
  path_provider: ^2.0.10
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  group_button: ^5.0.1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  flutter_animated_dialog: ^2.0.1
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  max_design:
    git:
      url: https://github.com/mmarchal/max_design.git
      ref: 0.1.0

dependency_overrides:
  # follow : https://github.com/dart-lang/mockito/issues/552
  code_builder: ^4.2.0
  
dev_dependencies:
  freezed: ^2.1.0
  retrofit_generator: ^4.0.1
  mockito: ^5.3.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  bloc_test: ^9.1.0


flutter:

  uses-material-design: true

  #To add assets to your application, add an assets section, like this:
  assets:
     - assets/config/
  #   - images/a_dot_ham.jpeg