name: max_sports
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.2.0
  build_runner: 
  path:
  path_provider: ^2.0.10
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  group_button: ^5.0.1
  http: ^0.13.4
  charts_flutter: 
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  flutter_animated_dialog: ^2.0.1

dev_dependencies:
  freezed: ^2.1.0
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg